### ISSUE TITLE
error in port 22 

### ISSUE THREAD

**Issue by noormohammedli** [LABORA-INF-UFG/eXP-RAN#1]
Hello Sir, 

in benchmarker steps i get an error after run the comment "sudo python benchmarker.py -b 50000 -p 1 -d 60 -s1 10 -s2 100"

<img width="736" alt="Screenshot 2021-09-19 at 6 09 19 pm" src="https://user-images.githubusercontent.com/34620715/133937456-b7b81382-7516-4892-bea5-7feca81943fa.png">

How can I solve this issue? 

Thanks, 
Noor

**Comment by joaopauloesper** [comment]
Dear Noor,

We responded your issue via the e-mail you sent us.

We provided detailed instructions in our response.

However, let us know if the problem still persists. We are happy to help.

Best regards.

**Comment by nil0819** [comment]
I am also facing the issue. I replaced my SSHD port with a new port. I think I need to change the sshd port in the VM I created but I do not know how to do that. Thank you in advance for your kind instruction. Also, it would be beneficial for everyone if you could share the solution in the readme file or tutorial.

**Comment by joaopauloesper** [comment]
Hi nil0819,

From what I understood from your issue, you are trying to run eXP-RAN in a VM, correct? This error in port 22 usually happens because of that, and most of the users no longer face this issue after they run eXP-RAN outside the VM, i.e., on their computer itself. The explanation for why that happens is here: https://github.com/LABORA-INF-UFG/eXP-RAN#virtualbox-considerations

Let me know if you are not running eXP-RAN inside a VM and/or are still facing this issue, I'm happy to help!

Also, you can contact us at expran.emulator@gmail.com for more help.
